### PR TITLE
Feature/milestone 4

### PR DESCRIPTION
**Pull request by GoRocco**
Conflicts resolved

### CODE REVIEW

**Comment by dgsbs** [comment]
**General**
* Fix Namespaces in all files
* All classes should be using `this.` before field access.


**`GitLogPresentation`**
* class `GitLogPresentation` add `this.` before fields.
* field `gitArgument` is unused.  There should be no unused fields in codebase.

**`GitProcess`**
* class `GitProcess` is doing `git log` and `git config` by using `RunGitProcess` which is fine but it uses GitLogArguments in order to launch `git config diff.renameLimit 999999`, which is bizzare.
  * Try creating new/other method arguments with better suit `git log` and `git diff`
* `RunGitProcess` should not care what git command is launch, differenciation using `arg.Contains("log")` shows poor design.
* `renameLimit` should be constant value  

**`Program`**
* `componentManager` and `commitManager` should be created (calling new) inside `ReportCreator` constructor.
* `GitLogPresentation` should access `ComponentManager` and `CommitManager` as public properties from `ReportCreator`. Also ideally those properties should be in ReadOnly mode.

**`ReportCreator`**
* property `IdNumber` can be private.
* Think about better names for `temporaryComponentManager`, `commitManager`, `componentManager` as the `...Manager` is often used as part of class name.
* Constant Values like `divideLine` and `smallLine` should be get from Config file.
  * `ReportCreator` and `GitProcess` should have one source of those strings, right now change in class requires remembering that we need to change same thing in other class. We should reduce risk of this happening.
* `CreateReportAllComoponents` have a typo.

**Comment by soltys** [comment]
**`ReportCreatorTests`**
```csharp
Dictionary<string, CommitData> commitManager = 
    new Dictionary<string, CommitData>();
Dictionary<string, ComponentData> componentManager = 
    new Dictionary<string, ComponentData>();
IJsonConfig jsonManager = new ReportCreatorTestsHelper();
ReportCreator reportCreator = new ReportCreator(jsonManager, componentManager,
                commitManager);
```

Should be created in test constructor to ensure that fields are fresh for each test.

**Raw strings**
```csharp
string testOutput = "divideLine\n" +
    "asdasdasd234234sedfdsf2323aewas23\n" +
    "Bruce Lee\n" +
    "05/02/2018\n" +
    "Changes needed\n" +
    "smallLine\n" +
    "33      3       Star/Wars//Ilike.txt\n" +
    "1       2       Common/Knowledge/Start/WhenReady.txt\n" +
    "1       1       Common/Knowledge/Start/Abort.txt\n" +
    "62      5       Computer/IsSlow/Why/Google.txt\n";
```
can be replaced with:
```csharp
const string testOutput = @"divideLine 
                           asdasdasd234234sedfdsf2323aewas23 
                           Bruce Lee 
                           05/02/2018 
                           Changes needed 
                           smallLine 
                           33      3       Star/Wars//Ilike.txt 
                           1       2       Common/Knowledge/Start/WhenReady.txt 
                           1       1       Common/Knowledge/Start/Abort.txt 
                           62      5       Computer/IsSlow/Why/Google.txt";
```                          

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/verbatim

**Comment by dgsbs** [comment]
**General**
* Use `var` where it's possible.
* Use fields instead of properties for private fields.
* Use `this.` for private fields, not for properties.

**GitReport**
Move `stdOneLine` closer to usage

**ComponentKey**
Should implement `IEqualitable<ComponentKey>`, learn how to do it properly. IEqualitable should be implemented for classes used as keys in Dictionary

**GitReportCreator**
Think how to refactor `AddCommitDataToList` in order to do not have out parameter

**GitLogPresentation**
* should not get whole `GitReportCreator` as `GitLogPresentation` do need access to `CreateFullReport`

**Comment by dgsbs** [comment]
**General**
* DO NOT USE  `this.` for properties.

**GitArguments**
* `GetDateSince` - should not have constant value added
* `GetDateSince` and `GetNumberOfDays` should be extracted to other class
  * timePeriod should be a enum
  * Code from extracted class should be unit-tests

**GitReportCreator**
* `CreateFullReport` it's not `out` usage is not required to function, `out` should be used as last resort.

**ComponentKey**
If class implements `IEquatable` it should also override `GetHashCode` and `Equals(object)` methods

**Comment by dgsbs** [comment]
**`ReportCreatorTests`**
* `CreateReport_ManyCommits_DictionaryKeysAreEqualToThoseIntededFromCommits` - do not use GetEnumerator, use check if key exists in dictionary.
* CreateReport_OneCommit_DataFromCreatedDictioanryEqualsToDataFromCommit - do not use GetEnumerator use if key exists then get value from that key
* Add test cases when there is multiple commits, with changes to diffrent components

**`ReportCreatorTestsHelper`**
* The name of `JsonConfigStub` would be a better fit for this class name

**`DateSinceManagerTestsHelper`**
* I don't get why would you need one.
* Why need to have interface to access converter between enum and days?

**`JsonConfig`**
* enum `Separator` should not be nested inside of class. Usually public enums are nested in namespace.

**`DaysNumber`**
* enum `FromToday` should not be nested inside of class. Usually public enums are nested in namespace.

**`HashIdKey`**
* Improve `GetHashCode` method https://stackoverflow.com/questions/263400/what-is-the-best-algorithm-for-an-overridden-system-object-gethashcode

**`GitReportCreator`**
* There is no needd to have completeDictionary as a field, it could be local variable inside of `CreateCompleteDictionary`
* think about better name insted of `CreateCompleteDictionary`
* fix typo in `CreateCompleteDictionary` - `dictioanryItem`

**`DateSinceManager`**
* if method is named `GetDateSince` I would expect that it would return `DateTime`

**`AllDataFromCommit`**
* Think about better name of this class

**Pull request merged**
